### ISSUE TITLE
Parameter `and_` should be `and`

### ISSUE THREAD

**Issue by bwindeler** [hide-ous/pytangle#34]
https://github.com/hide-ous/pytangle/blob/0ae59d3f9698e6769dbeaa84bbaa4c99aed783a8/pytangle/api.py#L322

Test case:
`curl https://api.crowdtangle.com/posts/search?token=[user_token]&and=test&startDate=2020-10-01T00%3A00%3A00&endDate=2020-10-01T23%3A59%3A59.999999&minInteractions=0&minSubscriberCount=0&offset=0&searchField=text_fields_and_image_text&searchTerm=case&sortBy=date&timeframe=6+HOUR&verifiedOnly=False&count=100`
returns status 200

`curl https://api.crowdtangle.com/posts/search?token=[user_token]&and_=test&startDate=2020-10-01T00%3A00%3A00&endDate=2020-10-01T23%3A59%3A59.999999&minInteractions=0&minSubscriberCount=0&offset=0&searchField=text_fields_and_image_text&searchTerm=case&sortBy=date&timeframe=6+HOUR&verifiedOnly=False&count=100`
returns status 400 `{"status":400,"code":20,"message":"Unknown parameters: and_"}`

Same is true for `not` vs `not_`

**Comment by hide-ous** [comment]
You're right, thanks for spotting it!
@Indiiigo could you add this to the open PR?

**Comment by Indiiigo** [comment]
Done.

**Comment by bwindeler** [comment]
Thank you!
